# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SmoothGeometry
                                 A QGIS plugin
 This plugin smooth a selected geometry
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-31
        copyright            : (C) 2021 by Valerio Pinna
        email                : pinnavalerio@yahoo.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SmoothGeometry class from file SmoothGeometry.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .smooth_geometry import SmoothGeometry
    return SmoothGeometry(iface)
